
spring:
  application:
    name: spring-boot-task-scheduler

server:
  port: 8085

# PushGateway
management:
  metrics:
    export:
      prometheus:
        pushgateway:
          enabled: true
          base-url: http://localhost:9091
          shutdown-operation: push
  endpoints:
    web:
      exposure:
        include: prometheus

#MANAGEMENT_METRICS_EXPORT_PROMETHEUS_PUSHGATEWAY_BASE-URL='host.docker.internal:9091'
